2022-12-12 16:03:05,002 INFO    MainThread:91775 [wandb_setup.py:_flush():68] Configure stats pid to 91775
2022-12-12 16:03:05,002 INFO    MainThread:91775 [wandb_setup.py:_flush():68] Loading settings from /Users/slavapirogov/.config/wandb/settings
2022-12-12 16:03:05,003 INFO    MainThread:91775 [wandb_setup.py:_flush():68] Loading settings from /Users/slavapirogov/pix2pix/wandb/settings
2022-12-12 16:03:05,003 INFO    MainThread:91775 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-12-12 16:03:05,003 INFO    MainThread:91775 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program': '/Users/slavapirogov/pix2pix/train.py'}
2022-12-12 16:03:05,003 INFO    MainThread:91775 [wandb_init.py:_log_setup():476] Logging user logs to /Users/slavapirogov/pix2pix/wandb/run-20221212_160304-288zymd2/logs/debug.log
2022-12-12 16:03:05,003 INFO    MainThread:91775 [wandb_init.py:_log_setup():477] Logging internal logs to /Users/slavapirogov/pix2pix/wandb/run-20221212_160304-288zymd2/logs/debug-internal.log
2022-12-12 16:03:05,004 INFO    MainThread:91775 [wandb_init.py:init():516] calling init triggers
2022-12-12 16:03:05,004 INFO    MainThread:91775 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {'__module__': 'configs.checkpoint_config', 'wandb_project': 'pix2pix', 'nc': 3, 'num_epochs': 200, 'save_epochs': 20, 'validate_epochs': 1, 'save_images': 1, 'batch_size': 10, 'save_path': 'checkpoint_weights', 'optim': 'Adam', 'learning_rate': 0.0002, 'beta1': 0.5, 'beta2': 0.999, 'mean': 0, 'std': 0.02, '__dict__': <attribute '__dict__' of 'CheckpointConfig' objects>, '__weakref__': <attribute '__weakref__' of 'CheckpointConfig' objects>, '__doc__': 'CheckpointConfig()', '__dataclass_params__': _DataclassParams(init=True,repr=True,eq=True,order=False,unsafe_hash=False,frozen=False), '__dataclass_fields__': {}, '__init__': <function __create_fn__.<locals>.__init__ at 0x7fc61f4b1670>, '__repr__': <function __create_fn__.<locals>.__repr__ at 0x7fc61f4b1550>, '__eq__': <function __create_fn__.<locals>.__eq__ at 0x7fc61f4b18b0>, '__hash__': None}
2022-12-12 16:03:05,005 INFO    MainThread:91775 [wandb_init.py:init():569] starting backend
2022-12-12 16:03:05,005 INFO    MainThread:91775 [wandb_init.py:init():573] setting up manager
2022-12-12 16:03:05,009 INFO    MainThread:91775 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-12-12 16:03:05,015 INFO    MainThread:91775 [wandb_init.py:init():580] backend started and connected
2022-12-12 16:03:05,032 INFO    MainThread:91775 [wandb_init.py:init():658] updated telemetry
2022-12-12 16:03:05,062 INFO    MainThread:91775 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2022-12-12 16:03:05,079 ERROR   MainThread:91775 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "/Users/slavapirogov/pix2pix/venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/Users/slavapirogov/pix2pix/venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 696, in init
    handle = backend.interface.deliver_run(run)
  File "/Users/slavapirogov/pix2pix/venv/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 719, in deliver_run
    run = self._make_run(run_obj)
  File "/Users/slavapirogov/pix2pix/venv/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 178, in _make_run
    self._make_config(data=config_dict, obj=proto_run.config)
  File "/Users/slavapirogov/pix2pix/venv/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 160, in _make_config
    update.value_json = json_dumps_safer(json_friendly(v)[0])
  File "/Users/slavapirogov/pix2pix/venv/lib/python3.9/site-packages/wandb/util.py", line 909, in json_dumps_safer
    return json.dumps(obj, cls=WandBJSONEncoder, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/slavapirogov/pix2pix/venv/lib/python3.9/site-packages/wandb/util.py", line 864, in default
    return json.JSONEncoder.default(self, obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type getset_descriptor is not JSON serializable
2022-12-12 16:03:08,796 WARNING MsgRouterThr:91775 [router.py:message_loop():77] message_loop has been closed
